# Generated by Django 4.2.10 on 2024-05-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentcompliance',
            name='paragraph1',
            field=models.CharField(db_index=True, default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='investmentcompliance',
            name='paragraph2',
            field=models.CharField(db_index=True, default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='investmentcompliance',
            name='paragraph3',
            field=models.CharField(db_index=True, default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='investmentcompliance',
            name='paragraph4',
            field=models.CharField(db_index=True, default='null', max_length=200),
        ),
    ]
