# Generated by Django 4.2.10 on 2024-05-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_investmentcompliance_paragraph1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationcompliance',
            name='paragraph10',
            field=models.TextField(db_index=True, default='null'),
        ),
        migrations.AddField(
            model_name='consultationcompliance',
            name='paragraph11',
            field=models.TextField(db_index=True, default='null'),
        ),
        migrations.AddField(
            model_name='consultationcompliance',
            name='paragraph12',
            field=models.TextField(db_index=True, default='null'),
        ),
        migrations.AddField(
            model_name='consultationcompliance',
            name='paragraph13',
            field=models.TextField(db_index=True, default='null'),
        ),
        migrations.AddField(
            model_name='consultationcompliance',
            name='paragraph14',
            field=models.TextField(db_index=True, default='null'),
        ),
        migrations.AddField(
            model_name='consultationcompliance',
            name='paragraph15',
            field=models.TextField(db_index=True, default='null'),
        ),
        migrations.AddField(
            model_name='consultationcompliance',
            name='paragraph16',
            field=models.TextField(db_index=True, default='null'),
        ),
        migrations.AddField(
            model_name='consultationcompliance',
            name='paragraph17',
            field=models.TextField(db_index=True, default='null'),
        ),
        migrations.AddField(
            model_name='consultationcompliance',
            name='paragraph18',
            field=models.TextField(db_index=True, default='null'),
        ),
        migrations.AddField(
            model_name='consultationcompliance',
            name='paragraph19',
            field=models.TextField(db_index=True, default='null'),
        ),
        migrations.AddField(
            model_name='consultationcompliance',
            name='paragraph20',
            field=models.TextField(db_index=True, default='null'),
        ),
        migrations.AddField(
            model_name='consultationcompliance',
            name='paragraph5',
            field=models.TextField(db_index=True, default='null'),
        ),
        migrations.AddField(
            model_name='consultationcompliance',
            name='paragraph6',
            field=models.TextField(db_index=True, default='null'),
        ),
        migrations.AddField(
            model_name='consultationcompliance',
            name='paragraph7',
            field=models.TextField(db_index=True, default='null'),
        ),
        migrations.AddField(
            model_name='consultationcompliance',
            name='paragraph8',
            field=models.TextField(db_index=True, default='null'),
        ),
        migrations.AddField(
            model_name='consultationcompliance',
            name='paragraph9',
            field=models.TextField(db_index=True, default='null'),
        ),
        migrations.AddField(
            model_name='investmentcompliance',
            name='paragraph10',
            field=models.TextField(db_index=True, default='null'),
        ),
        migrations.AddField(
            model_name='investmentcompliance',
            name='paragraph11',
            field=models.TextField(db_index=True, default='null'),
        ),
        migrations.AddField(
            model_name='investmentcompliance',
            name='paragraph12',
            field=models.TextField(db_index=True, default='null'),
        ),
        migrations.AddField(
            model_name='investmentcompliance',
            name='paragraph13',
            field=models.TextField(db_index=True, default='null'),
        ),
        migrations.AddField(
            model_name='investmentcompliance',
            name='paragraph14',
            field=models.TextField(db_index=True, default='null'),
        ),
        migrations.AddField(
            model_name='investmentcompliance',
            name='paragraph15',
            field=models.TextField(db_index=True, default='null'),
        ),
        migrations.AddField(
            model_name='investmentcompliance',
            name='paragraph16',
            field=models.TextField(db_index=True, default='null'),
        ),
        migrations.AddField(
            model_name='investmentcompliance',
            name='paragraph17',
            field=models.TextField(db_index=True, default='null'),
        ),
        migrations.AddField(
            model_name='investmentcompliance',
            name='paragraph18',
            field=models.TextField(db_index=True, default='null'),
        ),
        migrations.AddField(
            model_name='investmentcompliance',
            name='paragraph19',
            field=models.TextField(db_index=True, default='null'),
        ),
        migrations.AddField(
            model_name='investmentcompliance',
            name='paragraph20',
            field=models.TextField(db_index=True, default='null'),
        ),
        migrations.AddField(
            model_name='investmentcompliance',
            name='paragraph5',
            field=models.TextField(db_index=True, default='null'),
        ),
        migrations.AddField(
            model_name='investmentcompliance',
            name='paragraph6',
            field=models.TextField(db_index=True, default='null'),
        ),
        migrations.AddField(
            model_name='investmentcompliance',
            name='paragraph7',
            field=models.TextField(db_index=True, default='null'),
        ),
        migrations.AddField(
            model_name='investmentcompliance',
            name='paragraph8',
            field=models.TextField(db_index=True, default='null'),
        ),
        migrations.AddField(
            model_name='investmentcompliance',
            name='paragraph9',
            field=models.TextField(db_index=True, default='null'),
        ),
        migrations.AlterField(
            model_name='consultationcompliance',
            name='paragraph1',
            field=models.TextField(db_index=True, default='null'),
        ),
        migrations.AlterField(
            model_name='consultationcompliance',
            name='paragraph2',
            field=models.TextField(db_index=True, default='null'),
        ),
        migrations.AlterField(
            model_name='consultationcompliance',
            name='paragraph3',
            field=models.TextField(db_index=True, default='null'),
        ),
        migrations.AlterField(
            model_name='consultationcompliance',
            name='paragraph4',
            field=models.TextField(db_index=True, default='null'),
        ),
        migrations.AlterField(
            model_name='investmentcompliance',
            name='paragraph1',
            field=models.TextField(db_index=True, default='null'),
        ),
        migrations.AlterField(
            model_name='investmentcompliance',
            name='paragraph2',
            field=models.TextField(db_index=True, default='null'),
        ),
        migrations.AlterField(
            model_name='investmentcompliance',
            name='paragraph3',
            field=models.TextField(db_index=True, default='null'),
        ),
        migrations.AlterField(
            model_name='investmentcompliance',
            name='paragraph4',
            field=models.TextField(db_index=True, default='null'),
        ),
    ]
