# Generated by Django 4.2.10 on 2024-05-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_consultationcompliance_paragraph10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationcompliance',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='investmentcompliance',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
