# Generated by Django 4.2.13 on 2024-06-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_consultationcompliance_pdf_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentcompliance',
            name='paragraph1',
            field=models.TextField(blank=True, db_index=True, default='null'),
        ),
        migrations.AlterField(
            model_name='investmentcompliance',
            name='paragraph10',
            field=models.TextField(blank=True, db_index=True, default='null'),
        ),
        migrations.AlterField(
            model_name='investmentcompliance',
            name='paragraph11',
            field=models.TextField(blank=True, db_index=True, default='null'),
        ),
        migrations.AlterField(
            model_name='investmentcompliance',
            name='paragraph12',
            field=models.TextField(blank=True, db_index=True, default='null'),
        ),
        migrations.AlterField(
            model_name='investmentcompliance',
            name='paragraph13',
            field=models.TextField(blank=True, db_index=True, default='null'),
        ),
        migrations.AlterField(
            model_name='investmentcompliance',
            name='paragraph14',
            field=models.TextField(blank=True, db_index=True, default='null'),
        ),
        migrations.AlterField(
            model_name='investmentcompliance',
            name='paragraph15',
            field=models.TextField(blank=True, db_index=True, default='null'),
        ),
        migrations.AlterField(
            model_name='investmentcompliance',
            name='paragraph16',
            field=models.TextField(blank=True, db_index=True, default='null'),
        ),
        migrations.AlterField(
            model_name='investmentcompliance',
            name='paragraph17',
            field=models.TextField(blank=True, db_index=True, default='null'),
        ),
        migrations.AlterField(
            model_name='investmentcompliance',
            name='paragraph18',
            field=models.TextField(blank=True, db_index=True, default='null'),
        ),
        migrations.AlterField(
            model_name='investmentcompliance',
            name='paragraph19',
            field=models.TextField(blank=True, db_index=True, default='null'),
        ),
        migrations.AlterField(
            model_name='investmentcompliance',
            name='paragraph2',
            field=models.TextField(blank=True, db_index=True, default='null'),
        ),
        migrations.AlterField(
            model_name='investmentcompliance',
            name='paragraph20',
            field=models.TextField(blank=True, db_index=True, default='null'),
        ),
        migrations.AlterField(
            model_name='investmentcompliance',
            name='paragraph3',
            field=models.TextField(blank=True, db_index=True, default='null'),
        ),
        migrations.AlterField(
            model_name='investmentcompliance',
            name='paragraph4',
            field=models.TextField(blank=True, db_index=True, default='null'),
        ),
        migrations.AlterField(
            model_name='investmentcompliance',
            name='paragraph5',
            field=models.TextField(blank=True, db_index=True, default='null'),
        ),
        migrations.AlterField(
            model_name='investmentcompliance',
            name='paragraph6',
            field=models.TextField(blank=True, db_index=True, default='null'),
        ),
        migrations.AlterField(
            model_name='investmentcompliance',
            name='paragraph7',
            field=models.TextField(blank=True, db_index=True, default='null'),
        ),
        migrations.AlterField(
            model_name='investmentcompliance',
            name='paragraph8',
            field=models.TextField(blank=True, db_index=True, default='null'),
        ),
        migrations.AlterField(
            model_name='investmentcompliance',
            name='paragraph9',
            field=models.TextField(blank=True, db_index=True, default='null'),
        ),
    ]
