# Generated by Django 4.2.13 on 2024-06-05 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_mine_delete_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miningtrends',
            name='mine_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mine'),
        ),
    ]
