# Generated by Django 4.2.13 on 2024-06-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_miningtrends_mine_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miningtrends',
            name='international_cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='miningtrends',
            name='local_cost',
            field=models.FloatField(),
        ),
    ]
