# Generated by Django 4.2.13 on 2024-06-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_customuser_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='investments',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AddField(
            model_name='investments',
            name='contact',
            field=models.CharField(default='info@ties.co.tz', max_length=200),
        ),
        migrations.AddField(
            model_name='investments',
            name='modeOfInvestment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
