# Generated by Django 4.2.13 on 2024-06-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_investments_attachments_investments_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investments',
            name='projectStatus',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
