# Generated by Django 4.2.13 on 2024-07-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_premiummodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='investments',
            name='studiesDone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='capacity',
            field=models.CharField(db_index=True, default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='dimension',
            field=models.CharField(db_index=True, default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='grade',
            field=models.CharField(db_index=True, default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='groundedArea',
            field=models.CharField(db_index=True, default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='horsepower',
            field=models.CharField(db_index=True, default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='manufacturer',
            field=models.CharField(db_index=True, default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='physicalProperties',
            field=models.CharField(db_index=True, default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='qualityAssurance',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AddField(
            model_name='item',
            name='technicalDetails',
            field=models.CharField(db_index=True, default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='weight',
            field=models.CharField(db_index=True, default='null', max_length=200),
        ),
    ]
